In [1]:
using MAT
using JLD

In [2]:
Y = matread("original_data.mat")["dropSeq"]

10000×5000 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  2.0  0.0  …  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  2.0  4.0  0.0  0.0
 0.0  0.0  2.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  2.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  1.0  4.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  1.0  0.0  6.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  2.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  2.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  5.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  2.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  1.0  0.0  …  0.0  0.0  0.0  0.0  2.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  2.0  1.0  0.0
 0.0  0.0  3.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  3.0  0.0  0.0
 ⋮                     

In [3]:
M, N = size(Y)
Ynew = Y .- ((1/M) .* sum(Y, dims=1))

10000×5000 Matrix{Float64}:
 -0.0005  -0.0088  -0.019  -0.0397  …  -0.1101  -0.2221  -0.0014  -0.0002
 -0.0005  -0.0088   0.981  -0.0397     -0.1101  -0.2221   0.9986  -0.0002
 -0.0005   0.9912  -0.019  -0.0397      1.8899   3.7779  -0.0014  -0.0002
 -0.0005  -0.0088   1.981  -0.0397     -0.1101   1.7779  -0.0014  -0.0002
 -0.0005  -0.0088  -0.019  -0.0397      0.8899   3.7779  -0.0014  -0.0002
 -0.0005   0.9912  -0.019  -0.0397  …  -0.1101   5.7779  -0.0014  -0.0002
 -0.0005  -0.0088  -0.019  -0.0397      1.8899   0.7779  -0.0014  -0.0002
 -0.0005  -0.0088   0.981  -0.0397      1.8899   2.7779  -0.0014  -0.0002
 -0.0005  -0.0088  -0.019  -0.0397     -0.1101   4.7779  -0.0014  -0.0002
 -0.0005  -0.0088  -0.019  -0.0397     -0.1101   1.7779  -0.0014  -0.0002
 -0.0005  -0.0088   0.981  -0.0397  …  -0.1101   1.7779  -0.0014  -0.0002
 -0.0005  -0.0088  -0.019  -0.0397     -0.1101   1.7779   0.9986  -0.0002
 -0.0005  -0.0088   2.981  -0.0397     -0.1101   2.7779  -0.0014  -0.0002
  ⋮       

In [4]:
weight = sqrt.(sum(Ynew.^2, dims=1))
Ynew = Ynew./(ones(M)*weight)

10000×5000 Matrix{Float64}:
 -0.000223663  -0.000901791  -0.00130991  …  -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.0676327       0.267074     -0.000141436
 -0.000223663   0.101574     -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.136575       -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663   0.101574     -0.00130991  …  -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.0676327      -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.0676327   …  -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991      0.267074     -0.000141436
 -0.000223663  -0.000901791   0.205518       -0.000374428  -0.000141436
  ⋮                                 

In [5]:
Ynew = [ isnan(x) ? 0 : x for x in Ynew ]

10000×5000 Matrix{Real}:
 -0.000223663  -0.000901791  -0.00130991  …  -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.0676327       0.267074     -0.000141436
 -0.000223663   0.101574     -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.136575       -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663   0.101574     -0.00130991  …  -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.0676327      -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991     -0.000374428  -0.000141436
 -0.000223663  -0.000901791   0.0676327   …  -0.000374428  -0.000141436
 -0.000223663  -0.000901791  -0.00130991      0.267074     -0.000141436
 -0.000223663  -0.000901791   0.205518       -0.000374428  -0.000141436
  ⋮                                    

In [6]:
sum(isnan.(Ynew))

0

In [7]:
sum(isinf.(Ynew))

0

In [8]:
Ynew = Float64.(Ynew);
Ynew = 1e3 .* Ynew

10000×5000 Matrix{Float64}:
 -0.223663   -0.901791   -1.30991  …  -3.66434   -0.374428  -0.141436
 -0.223663   -0.901791   67.6327      -3.66434  267.074     -0.141436
 -0.223663  101.574      -1.30991     62.3301    -0.374428  -0.141436
 -0.223663   -0.901791  136.575       29.3329    -0.374428  -0.141436
 -0.223663   -0.901791   -1.30991     62.3301    -0.374428  -0.141436
 -0.223663  101.574      -1.30991  …  95.3273    -0.374428  -0.141436
 -0.223663   -0.901791   -1.30991     12.8343    -0.374428  -0.141436
 -0.223663   -0.901791   67.6327      45.8315    -0.374428  -0.141436
 -0.223663   -0.901791   -1.30991     78.8287    -0.374428  -0.141436
 -0.223663   -0.901791   -1.30991     29.3329    -0.374428  -0.141436
 -0.223663   -0.901791   67.6327   …  29.3329    -0.374428  -0.141436
 -0.223663   -0.901791   -1.30991     29.3329   267.074     -0.141436
 -0.223663   -0.901791  205.518       45.8315    -0.374428  -0.141436
  ⋮                                ⋱                        
 

In [9]:
using Random
index = randperm(5000)[1:5000];

In [10]:
Ytrain = Ynew[:,index[1:2500]]
Ytest = Ynew[:,index[2501:end]]
save("original_data.jld", "train", Ytrain, "test", Ytest)